import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { DocumentTextIcon, ArrowLeftIcon } from '@heroicons/react/24/outline';

const WhatIfPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [document, setDocument] = useState(null);
  const [loading, setLoading] = useState(true);
  const [scenarios, setScenarios] = useState([]);
  const [newScenario, setNewScenario] = useState('');

  useEffect(() => {
    // In a real app, fetch document data
    setLoading(false);
    setDocument({
      id,
      name: 'Sample Document',
      type: 'Contract'
    });
  }, [id]);

  const handleAddScenario = () => {
    if (newScenario.trim()) {
      const scenario = {
        id: Date.now(),
        question: newScenario,
        analysis: `This is a sample analysis for: "${newScenario}". In a real implementation, this would be generated by AI based on the document content and the what-if scenario.`,
        timestamp: new Date().toLocaleString()
      };
      setScenarios([...scenarios, scenario]);
      setNewScenario('');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Navigation */}
      <nav className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <div className="flex items-center">
              <DocumentTextIcon className="h-8 w-8 text-blue-600 mr-3" />
              <span className="text-2xl font-bold text-gray-900">
                What-If Analysis
              </span>
            </div>
            <button
              onClick={() => navigate(`/analysis/${id}`)}
              className="flex items-center text-gray-600 hover:text-gray-900 transition-colors"
            >
              <ArrowLeftIcon className="h-5 w-5 mr-1" />
              Back to Analysis
            </button>
          </div>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Scenario Planning
          </h1>
          <p className="text-gray-600">
            Explore different "what if" scenarios for {document?.name}
          </p>
        </div>

        {/* Scenario Input */}
        <div className="bg-white rounded-xl shadow-lg p-6 mb-8">
          <h2 className="text-xl font-semibold mb-4">Ask a "What If" Question</h2>
          <div className="flex gap-4">
            <input
              type="text"
              value={newScenario}
              onChange={(e) => setNewScenario(e.target.value)}
              placeholder="e.g., What if the contract is terminated early?"
              className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              onKeyPress={(e) => e.key === 'Enter' && handleAddScenario()}
            />
            <button
              onClick={handleAddScenario}
              className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
            >
              Analyze
            </button>
          </div>
        </div>

        {/* Scenarios */}
        <div className="space-y-6">
          {scenarios.length === 0 ? (
            <div className="bg-white rounded-xl shadow-lg p-8 text-center">
              <p className="text-gray-500 text-lg">
                No scenarios analyzed yet. Ask a "what if" question above to get started.
              </p>
            </div>
          ) : (
            scenarios.map((scenario) => (
              <div key={scenario.id} className="bg-white rounded-xl shadow-lg p-6">
                <div className="mb-4">
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    {scenario.question}
                  </h3>
                  <p className="text-sm text-gray-500">{scenario.timestamp}</p>
                </div>
                <div className="prose max-w-none">
                  <p className="text-gray-700">{scenario.analysis}</p>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
};

export default WhatIfPage;
